# Aigis will run from same directory where this config file resides
# All paths should be relative to there
name: Styleguide

# The directory containing the source files to parse recursively
source:
  # - ./css
  # - ./demo.md
  - ../../../../htdocs/assets/css/

# The types that aigis will scan to document comment
source_type:
  - .styl
  - .css
  - .sass
  - .scss

# The directory that aigis will build to
dest: ../../../../../html/_styleguide

# The assets needed to build the docs
# You may put doc related assets here too: images, css, etc.
dependencies:
  - ./aigis_assets
  # - ../../../../../html/assets

# Index page created from markdown file
index: ./index.md

# You can choose template engine : ejs, jade, handlebars
template_engine: jade
# template_engine: ejs

# The directory containing the tempalte files to generate pages
# It must contain 'layout.xxx' and 'index.xxx' (.ejs or .jade or .hbs)
template_dir: ./template_html
# template_dir: ./template_ejs

# Aigis displays logs
log: false

# When you don't want color palette page (color.html) you may set false
color_palette: true

#
transform:
  - html
#  - ejs
#  - jade

# Aigis
timestamp_format: 'YYYY/MM/DD'

preview_class: aigis-preview

component_dir: ./html

output_collection:
  - category
  - tag

highlight: true
highlight_theme: okadia
lang_prefix: 'language-'

#helper_options:
#  - disable_link_index: true

